/*
Created by abuchegger on 2020-11-27.
This file is part of the software provided by ARTI
Copyright (c) 2020, ARTI
All rights reserved.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef ARTI_MOVEMENT_SKILL_INTERFACE_ABSTRACT_MOVEMENT_SKILL_H
#define ARTI_MOVEMENT_SKILL_INTERFACE_ABSTRACT_MOVEMENT_SKILL_H

#include <arti_movement_skill_interface/movement_skill_interface.h>

namespace arti_movement_skill_interface
{

class AbstractMovementSkill : public MovementSkillInterface
{
public:
  void initialize(
    std::string name, const ros::NodeHandle& node_handle, ResultCB finished_with_success_cb,
    ResultCB finished_with_failure_cb) override;

protected:
  std::string name_;
  ros::NodeHandle node_handle_;
  ResultCB finished_with_success_cb_;
  ResultCB finished_with_failure_cb_;
};

}

#endif //ARTI_MOVEMENT_SKILL_INTERFACE_ABSTRACT_MOVEMENT_SKILL_H
